export {default as LandingPage} from './LandingPage'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Region} from './Region'
export {default as Article} from './Article'
export {default as Destinations} from './Destinations'
export {default as UserProfile} from './UserProfile'
export {default as AddArticle} from './AddArticle'